spring.application.name=pratica
spring.datasource.url=jdbc:sqlite:./pratica.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.data.open-in-view=false
logging.level.org.hibernate.orm.jdbc.bind=TRACE